services:
  - type: web
    name: cashmoney
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: admin@cashmoney.com
      - key: WALLET_USDT
        value: 0xE4901E78F8c92199bAfD93AD87C5a250C48199c2
